#ifndef ENUMS_CPP
#define ENUMS_CPP

// Enumération des langues disponibles
enum LANGUAGE {
    FRENCH,
    ENGLISH,
    GERMAN,
    LANGUAGES_NUMBER
};

// Enumération des clés 
enum KEY {
    // Overlay Layout
    LBL_POWDER_TASK_SYSTEMS,
    IMG_CLOUD,
    IMG_WIFI,
    BTN_PARAMS,
    // Accueil
    PROGRESS_BAR,
    // Dashbord measurements
    LBL_ACTUAL_SERIE,
    LBL_ACTUAL_SERIE_POWDER,
    LBL_SERIE_POURCENTAGE,
    BTN_NEW_MEASURE,
    BTN_MEASURE_HISTORY,
    BTN_FINAL_MEASURE,
    // Dashbord Powders
    LBL_POWDER_INFO,
    LBL_POWDER_INFO_POWDER,
    LBL_IS_ACTUAL_SERIE,
    // Weight measure
    BTN_AUTO_CALIBRATION,
    BTN_MANUAL_CALIBRATION,
    LBL_POWDER_COLOR_WM,
    LBL_WEIGHT,
    LBL_WEIGHT_UNIT,
    BTN_VALIDATE_WM,
    BTN_RTN_TO_DASHBORD_WM,
    // Parameters
    LBL_P_SYSTEM,
    LBL_P_USER,
    BTN_PARAM_CALIBRATION,
    BTN_PARAM_UNIT,
    BTN_PARAM_LANGUAGE,
    BTN_PARAM_WIFI,
    BTN_PARAM_LOGIN,
    BTN_RTN_FROM_P,
    // Manual Calibration
    LBL_TITILE_MC,
    LBL_RED_INSTRUCT,
    LBL_DESCRIPTION_P_MC,
    EDT_WEIGHT_REFERENCE,
    LBL_WEIGHT_USED_P_MC,
    BTN_VALIDAE_P_MC,
    BTN_RTN_FROM_P_MC,
    BTN_INFO_P_MC,
    LBL_MORE_INFORMATION_P_MC,
    // Unit
    LBL_TITLE_UNIT,
    RB_KG,
    RB_LB,
    BTN_VALIDATE_P_U,
    BTN_RTN_FROM_P_U,
    // Language
    LBL_TITLE_LANG,
    RB_FRENCH,
    RB_ENGLISH,
    RB_GERMAN,
    BTN_VALIDATE_P_LANG,
    BTN_RTN_FROM_P_LANG,
    // Wifi
    LBL_TITLE_WIFI,
    LBL_SSID,
    EDT_SSID,
    LBL_PASSWORD_WIFI,
    EDT_PASSWORD_WIFI,
    BTN_VALIDATE_P_WIFI,
    BTN_RTN_FROM_P_WIFI,
    BTN_CONTINUE_WHITOUT_WIFI,
    // Login
    LBL_TITLE_LOG,
    LBL_EMAIL_CONNECTION,
    EDT_EMAIL_CONNECTION,
    LBL_PASSWORD_LOGIN,
    EDT_PASSWORD_LOGIN,
    BTN_VALIDATE_P_LOGIN,
    BTN_RTN_FROM_P_LOGIN,
    BTN_CONTINUE_WHITOUT_LOGIN,
    // Alert Pop Up
    LBL_TITLE_ALERT_PUP,
    LBL_DESCRIPTION_ALERT_PUP,
    LBL_DESCRIPTION2_ALERT_PUP,
    // Dialogue
    LBL_TOP_TITLE_DIAG_MC,
    BTN_CLOSE_DIAG_MC,
    LBL_DESCRIPTION_DIAG_MC,
    LBL_WEIGHT_REFERENCE_DIAG_MC,
    LBL_WHEIGT_USED_DIAG_MC,
    LBL_QUESTION_DIAG_MC,
    BTN_CONTINUE_DIAG_MC,
    BTN_CANCEL_DIAG_MC
};

// Enumération des unités de température
enum UNITY_WEIGHT
{
    UNITY_LB,
    UNITY_KG
};

enum PAGE
{
    // Layout
    OVERLAY_LAYOUT,
    // Loading
    HOME_PAGE,
    //Principal
    W_DASBOARD,
    W_WEIGHT_MEASURE,
    // Paramters
    W_PARAMS,
    W_PARAM_MANUAL_CALIBRATION,
    W_PARAM_UNIT,
    W_PARAM_LANGUAGE,
    W_PARAM_WIFI,
    W_PARAM_LOGIN,
    //Other
    PUP_ALERTE,
    PUP_MORE_ABOUT_MC,
    DIAG_MC
};
#endif